package com.jiuzhuan.jsdroid.utils

import android.accessibilityservice.AccessibilityService

val GLOBAL_ACTION_BACK: Int = AccessibilityService.GLOBAL_ACTION_BACK
val GLOBAL_ACTION_HOME: Int = AccessibilityService.GLOBAL_ACTION_HOME
val GLOBAL_ACTION_POWER_DIALOG: Int = AccessibilityService.GLOBAL_ACTION_POWER_DIALOG
val GLOBAL_ACTION_NOTIFICATIONS: Int = AccessibilityService.GLOBAL_ACTION_NOTIFICATIONS
val GLOBAL_ACTION_QUICK_SETTINGS: Int = AccessibilityService.GLOBAL_ACTION_QUICK_SETTINGS
val GLOBAL_ACTION_RECENTS: Int = AccessibilityService.GLOBAL_ACTION_RECENTS
val GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN: Int = AccessibilityService.GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN
val GLOBAL_ACTION_TAKE_SCREENSHOT: Int = AccessibilityService.GLOBAL_ACTION_TAKE_SCREENSHOT
val GLOBAL_ACTION_LOCK_SCREEN: Int = AccessibilityService.GLOBAL_ACTION_LOCK_SCREEN

val REQUEST_CODE_SCREEN_CAPTURE: Int = 1001
val REQUEST_CODE_MANAGE_STORAGE: Int = 1002


val BROADCAST_ACTION_SCREENCAPTURER: String = "SCREENCAST"
val BROADCAST_ACTION_START: String = "BROADCAST_ACTION_START"
val BROADCAST_ACTION_STOP: String = "BROADCAST_ACTION_STOP"
val BROADCAST_ACTION_MESSAGE: String = "BROADCAST_ACTION_MESSAGE"
val BROADCAST_ACTION_CHANGE_POSITION: String = "BROADCAST_ACTION_CHANGE_POSITION"
val BROADCAST_GAMES_OVER: String = "BROADCAST_GAMES_OVER"


class Const {

}